In [ ]:
!pip3 install torch torchvision torchaudio

In [2]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print("ndim : ",n_array.ndim, "shape : ", n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim :  2 shape :  (2, 5)


In [3]:
import torch
t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim : ",t_array.ndim, "shape : ", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim :  2 shape :  torch.Size([2, 5])


In [4]:
print(t_array.shape)
print(t_array.ndim)
print(t_array.size())

torch.Size([2, 5])
2
torch.Size([2, 5])


In [5]:
# list data to tensor
data = [[3,5], [10,5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

In [6]:
# ndarray to tensor
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]], dtype=torch.int32)

In [7]:
# numpy like operations
data = [[3, 5, 20], [10, 5, 50], [1, 5, 10]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5, 20],
        [10,  5, 50],
        [ 1,  5, 10]])

In [8]:
x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [9]:
x_data[:2, 1:]

tensor([[ 5, 20],
        [ 5, 50]])

In [10]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [11]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [12]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]], dtype=int64)

In [13]:
x_data.shape

torch.Size([3, 3])

In [14]:
x_data.dtype

torch.int64

In [15]:
x_data.device

device(type='cpu')

In [18]:
!pip install https://download.pytorch.org/whl/cu102/torch_stable.html --user

  ERROR: Cannot unpack file C:\Users\DAUNJEON\AppData\Local\Temp\pip-unpack-25m8_nh0\torch_stable.html (downloaded from C:\Users\DAUNJEON\AppData\Local\Temp\pip-req-build-5jap1xh9, content-type: text/html); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\DAUNJEON\AppData\Local\Temp\pip-req-build-5jap1xh9


In [17]:
!pip3 install torch==1.10.1+cu102 torchvision==0.11.2+cu102 torchaudio===0.10.1+cu102 -f

Looking in links: https://download.pytorch.org/whl/cu102/torch_stable.html

ERROR: Could not install packages due to an OSError: [WinError 5] 액세스가 거부되었습니다: 'c:\\users\\daunjeon\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\~orch\\lib\\asmjit.dll'
Consider using the `--user` option or check the permissions.




  Attempting uninstall: torch
    Found existing installation: torch 1.10.1
    Uninstalling torch-1.10.1:
      Successfully uninstalled torch-1.10.1


In [21]:
# gpu 사용
if torch.cuda.is_available():
    x_data_cuda = x_data.to('cuda')
    x_data_cuda.device

In [ ]:
# view : reshape과 동일하게  tensor의 shape을 변환
# squeeze : 차원의 개수가 1인 차원을 삭제
# unsqueeze : 차원의 개수가 1인 차원을 추가

In [22]:
# Tensor handling
tensor_ex = torch.rand(size=(2,3,2))
tensor_ex

tensor([[[0.3147, 0.8925],
         [0.1034, 0.0595],
         [0.5181, 0.6945]],

        [[0.5917, 0.5608],
         [0.4163, 0.8618],
         [0.8888, 0.6126]]])

In [23]:
tensor_ex.view([-1, 6])

tensor([[0.3147, 0.8925, 0.1034, 0.0595, 0.5181, 0.6945],
        [0.5917, 0.5608, 0.4163, 0.8618, 0.8888, 0.6126]])

In [24]:
tensor_ex.reshape([-1, 6])

tensor([[0.3147, 0.8925, 0.1034, 0.0595, 0.5181, 0.6945],
        [0.5917, 0.5608, 0.4163, 0.8618, 0.8888, 0.6126]])

In [25]:
a = torch.zeros(3,2)
b = a.view(2,3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [26]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [27]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [31]:
a = torch.zeros(3,2)
b = a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [32]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [33]:
b

tensor([0., 0., 0., 0., 0., 0.])

In [38]:
# squeeze unsqueeze
tensor_ex = torch.rand(size=(2,1,2))
tensor_ex.squeeze().shape

torch.Size([2, 2])

In [35]:
tensor_ex = torch.rand(size=(2,2))
tensor_ex.unsqueeze(0).shape

torch.Size([1, 2, 2])

In [36]:
tensor_ex = torch.rand(size=(2,2))
tensor_ex.unsqueeze(1).shape

torch.Size([2, 1, 2])

In [37]:
tensor_ex = torch.rand(size=(2,2))
tensor_ex.unsqueeze(2).shape

torch.Size([2, 2, 1])

In [39]:
# tensor operations
n1 = np.arange(10).reshape(2,5)
t1 = torch.FloatTensor(n1)

In [40]:
t1+t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

In [41]:
t1-t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [42]:
t1+10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [44]:
# 행렬곱셈 연산은 dot이 아닌 mm 사용!
n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)
t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [45]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [49]:
t1.dot(t2)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [46]:
# dot 은 scalar or vector일 때는 문제 없다.
a = torch.rand(10)
b = torch.rand(10)
a.dot(b)

tensor(2.4438)

In [47]:
a

tensor([0.4831, 0.4160, 0.2703, 0.0968, 0.6100, 0.0179, 0.1909, 0.5313, 0.9253,
        0.4834])

In [48]:
a.mm(b)

RuntimeError: self must be a matrix

In [54]:
# mm vs matmul(broadcasting)
a = torch.rand(5, 2, 3)
b = torch.rand(5)
a.mm(b)

RuntimeError: self must be a matrix

In [56]:
a = torch.rand(5, 2, 3)
b = torch.rand(3)
a.matmul(b)

tensor([[0.3900, 0.8087],
        [1.0734, 0.1269],
        [0.7500, 0.4394],
        [1.0381, 0.5299],
        [1.1470, 0.6882]])

In [60]:
# a[0].mm(torch.unsqueeze(b,1))
# a[1].mm(torch.unsqueeze(b,1))
# a[2].mm(torch.unsqueeze(b,1))
# a[3].mm(torch.unsqueeze(b,1))
# a[4].mm(torch.unsqueeze(b,1))
for i in range(5):
    print(a[i].mm(torch.unsqueeze(b,1)).squeeze())

tensor([0.3900, 0.8087])
tensor([1.0734, 0.1269])
tensor([0.7500, 0.4394])
tensor([1.0381, 0.5299])
tensor([1.1470, 0.6882])


In [61]:
# Tensor operatios for ML/DL formula
import torch
import torch.nn.functional as F

tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [62]:
y = torch.randint(5, (10,5))
y_label = y.argmax(dim=1)
y, y_label

(tensor([[2, 0, 3, 0, 4],
         [1, 4, 3, 0, 3],
         [0, 1, 1, 1, 3],
         [3, 1, 4, 0, 3],
         [1, 4, 2, 0, 4],
         [0, 1, 2, 1, 1],
         [4, 0, 1, 0, 1],
         [3, 2, 2, 2, 2],
         [3, 0, 1, 3, 4],
         [3, 0, 4, 4, 2]]),
 tensor([4, 1, 4, 2, 1, 2, 0, 0, 4, 2]))

In [63]:
torch.nn.functional.one_hot(y_label)

tensor([[0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0]])

In [64]:
import itertools
a = [1, 2, 3]
b = [4, 5]
list(itertools.product(a,b))

[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]

In [65]:
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

C:\Users\DAUNJEON\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\functional.py:1069: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2157.)
  return _VF.cartesian_prod(tensors)  # type: ignore[attr-defined]


tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

In [67]:
# AutoGrad 자동 미분
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 10*y + 25
z.backward()
w.grad

tensor(40.)

In [68]:
# vector 편미분
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

a.grad

tensor([36., 81.])

In [69]:
b.grad

tensor([-12.,  -8.])