## input output cnt 개념 이해하기

In [1]:
# XOR 문제에서의 input output cnt

# 값이 변화하는 매개변수의 개수 (0,0), (0,1), (1,0), (1,1), 매개변수는 2개
input_cnt = 2
# 추론하는 값이 0인지 1인지 확인하므로 매개변수는 1개
output_cnt = 1

## 무작위로 가중치 생성하는 방법

In [2]:
import numpy as np

input_cnt = 3
output_cnt = 1

# 학습 데이터(임의)
input_x = [[0.12, 1.02, 4.1],[0.15,5.12,12.2]] 

# 종속 변수(임의)
label_y = [[5],[3]]
input_x_shape = np.array(input_x)
print("input_x: \n", input_x_shape)
print("\ninput_x_shape: ", input_x_shape.shape)

np.random.seed(seed=100)

# 정규분포 중에 값을 랜덤으로 생성,  loc(평균값), scale(표준편차), size(몇 개 생성?)
theta_1 = np.random.normal(loc = 0, scale = 1, size = [input_cnt, output_cnt]) 
print("\ntheta_1: \n", theta_1)
print("\ntheta_1_shape: ", theta_1.shape)
# theta_0 = np.random.normal(loc = 0, scale = 1, [output_cnt])
theta_0 = np.random.normal(0, 1, [output_cnt])
print("\ntheta_0: ", theta_0)

# 행렬 곱 연산을 빠르게 할 수 있는 도구
y_hat = np.matmul(input_x, theta_1) + theta_0
print("\ny_hat: \n", y_hat)
print("\nlabel_y: \n", label_y)
# y_hat과 label_y이 비슷해지기 위한 가중치를 조정

input_x: 
 [[ 0.12  1.02  4.1 ]
 [ 0.15  5.12 12.2 ]]

input_x_shape:  (2, 3)

theta_1: 
 [[-1.74976547]
 [ 0.3426804 ]
 [ 1.1530358 ]]

theta_1_shape:  (3, 1)

theta_0:  [-0.25243604]

y_hat: 
 [[ 4.61457291]
 [15.3066596 ]]

label_y: 
 [[5], [3]]


## Loss Funtion : MSE

In [3]:
y_hat[0]

a = (y_hat[0]-label_y[0])**2
b = (y_hat[1]-label_y[1])**2


print("theta_0 : " , theta_0)
print("theta_1 : " , theta_1)

mse = (a+b)/2

print("mse : " , mse)

theta_0 :  [-0.25243604]
theta_1 :  [[-1.74976547]
 [ 0.3426804 ]
 [ 1.1530358 ]]
mse :  [75.80121226]


## Dict를 활용한 매개변수 관리

In [4]:
import numpy as np

input_cnt = 3
output_cnt = 1

input_x = [[0.12, 1.02, 4.1],[0.15,5.12,12.2]] 
label_y = [[5],[3]]
input_x_shape = np.array(input_x)
print("input_x_shape: ", input_x_shape.shape)

theta_1 = np.random.normal(loc = 0, scale = 1, size = [input_cnt, output_cnt]) 
print("theta_1_shape: ", theta_1.shape)
theta_0 = np.random.normal(0, 1, [output_cnt])

# ------------------------------------------------------------------
# dictionary parameter management
# ------------------------------------------------------------------

# w : weight, b : bias
parameter = {'w' : theta_1, 'b' : theta_0}

y_hat = np.matmul(input_x, parameter['w']) + parameter['b'] 

# ------------------------------------------------------------------


input_x_shape:  (2, 3)
theta_1_shape:  (3, 1)


## dictionary get(key, basic_value)

In [5]:
data = {'a' : 123}
print(data.get('b', 123))

123


## if elif else Condition

In [6]:
# loss = 14
loss = float(input("Now LOSS : "))

if loss <= 5:
    print('Learning Successful.')
elif loss <= 10:
    print('Learning Failed.')
elif loss <= 15:
    print('Learning Failed. Adjust Learning Rate.')    
else:
    print('Model Init')

KeyboardInterrupt: Interrupted by user

## in & not in (with exercise)

In [ ]:
user_1 = {'name' : 'AI_BOT_1', 'email' : 'AI_BOT_1@abcdef.com', 'age' : 1}
user_2 = {'name' : 'AI_BOT_2', 'email' : 'AI_BOT_2abcdef.com', 'age' : 1}
user_3 = {'name' : 'AI_BOT_3', 'age' : 1}

In [ ]:
caution = '[주의] 다음사항을 확인해주세요.'
error = '[Error code] : '
success = '[success] '
# -------------------------------------------------
# user_1
# -------------------------------------------------
print("[LOG-IN] user_1\n"+'-'*50)
if 'email' in user_1:
    if '@' not in user_1['email']:
        print(error + "Email Address Error\n")
    else:
        print(success + "Email : " + user_1['email']+'\n')
elif 'name' not in user_1:
    print(caution)
    print(error + "No name\n")
elif 'age' not in user_1:
    print(caution)
    print(error + "No age\n")
else:
    print(caution)
    print(error + "No email\n")

# -------------------------------------------------
# user_2
# -------------------------------------------------
print("[LOG-IN] user_2\n"+'-'*50)    
if 'email' in user_2:
    if '@' not in user_2['email']:
        print(caution)
        print(error + "Email Address Error\n")
    else:
        print(success + "Email : " + user_1['email']+'\n')
elif 'name' not in user_2:
    print(caution)
    print(error + "No name\n")
elif 'age' not in user_2:
    print(caution)
    print(error + "No age\n")
else:
    print(caution)
    print(error + "No email\n")

# -------------------------------------------------
# user_3
# -------------------------------------------------
print("[LOG-IN] user_3\n"+'-'*50)    
if 'email' in user_3:
    if '@' not in user_3['email']:
        print(caution)
        print(error + "Email Address Error\n")
    else:
        print(success + "Email : " + user_1['email']+'\n')
elif 'name' not in user_3:
    print(caution)
    print(error + "No name\n")
elif 'age' not in user_3:
    print(caution)
    print(error + "No age\n")
else:
    print(caution)
    print(error + "No email\n")

## One-hot Vector Exercise
### 내가 원하는 값에 불을 켜다!

In [ ]:
import numpy as np

#rows = ['M',0.455,0.365,0.095]
#rows = ['F',0.455,0.365,0.095]
rows = ['I',0.455,0.365,0.095]

# 버퍼 : 임시 공간 생성
data = np.zeros(6)
print('data :\n', data)

In [ ]:
if rows[0] == 'M':
    data[0] = 1
elif rows[0] == 'F': 
    data[1] = 1
elif rows[0] == 'I': 
    data[2] = 1     

print('data :\n', data)

In [ ]:
data[3:] = rows[1:]
print('data :\n', data)

## enter exit Exercise

In [ ]:
user_log = []
for i in range(3):
    ID = input("Enter your ID : ")
    age = float(input("Enter your Age as a Number :"))

    user = {'ID':ID, 'age':age, 'state':''}


    if age <= 15:
        user['state'] = 'Access denied'
        print("Manage System : Sorry {}. ".format(ID)+ "You can't Enter.")
    else:
        user['state'] = "Success"
        print("{}, Have a Good Time.".format(ID))
    
    user_log.append(user)
    
for i in user_log:
    print(i)


In [ ]:
import os
print(os.getcwd())

In [ ]:
import csv
import numpy as np

with open('data/abalone_mini.csv') as csvfile:
    csv_reader = csv.reader(csvfile)
    #print(type(csv_reader))
    
    rows = []
    for row in csv_reader:
        rows.append(row)
        
    #print(rows)
    
    data = np.zeros([5,11])
    
    for n,row in enumerate(rows):
        #print(row)
        if row[0] == 'I':data[n,0] = 1
        elif row[0] == 'M':data[n,1] = 1
        elif row[0] == 'F':data[n,2] = 1
        
        data[n, 3:] = row[1:]
        
    print(data)

In [ ]:
import pandas as pd

df = pd.read_csv('data/abalone_mini.csv', header = None)
df

## while loop exercise

In [42]:
game = input('Input Next Action : ')
count = 1
while game != 'gg' and game != 'GG':
    
    print('your Action-'+str(count)+' : ', game)
    game = input('Input Next Action : ')
    count += 1
    
print('Game Over')

Input Next Action :  gg


Game Over


In [31]:
count = 0
while True:
    game = input('Input Next Action : ')
    count += 1
    if game == 'gg' or game == 'GG':
        break
    print('your Action-'+str(count)+' : ', game)

print('Game Over')

Input Next Action :  gg


Game Over


## function exercise

In [51]:
# LOL 게임 시나리오
K_name = '케이틀린'
K_hp = 400
K_damage = 50

print('"{0}"님이 소환사의 협곡에 참여하였습니다.'.format(K_name))
print("hp : {0}, damage : {1}".format(K_hp, K_damage))

"케이틀린"님이 소환사의 협곡에 참여하였습니다.
hp : 400, damage : 50


In [52]:
N_name = '누누'
N_hp = 550
N_damage = 70

print('"{0}"님이 소환사의 협곡에 참여하였습니다.'.format(N_name))
print("hp : {0}, damage : {1}".format(N_hp, N_damage))

"누누"님이 소환사의 협곡에 참여하였습니다.
hp : 550, damage : 70


In [48]:
def attack(name, location, damage):
    print("{0} : 공격을 {1} 방향으로 실행하였습니다. [Damage : {2}]"\
          .format(name,location,damage))

In [53]:
attack(K_name, "왼쪽", K_damage)
attack(N_name, "오른쪽", N_damage)

케이틀린 : 공격을 왼쪽 방향으로 실행하였습니다. [Damage : 50]
누누 : 공격을 오른쪽 방향으로 실행하였습니다. [Damage : 70]


In [54]:
def game_system():
    print("<Game System>")

In [55]:
def attack(name, location, damage):
    game_system()
    print("{0} : 공격을 {1} 방향으로 실행하였습니다. [Damage : {2}]"\
          .format(name,location,damage))

In [56]:
attack(K_name, "왼쪽", K_damage)
attack(N_name, "오른쪽", N_damage)

<Game System>
케이틀린 : 공격을 왼쪽 방향으로 실행하였습니다. [Damage : 50]
<Game System>
누누 : 공격을 오른쪽 방향으로 실행하였습니다. [Damage : 70]


## 가중치나 편향값 초기화

In [60]:
import numpy as np
# 이 함수는 파라미터(가중치[세타1], 편향[세타0])를 초기화 시켜주는 함수입니다.

RND_mean = 0
RND_std = 1

input_cnt = 10 # 독립 변수의 수
output_cnt = 1 # 종속 변수의 수

def model_init():
    global weight, bias # 전역 변수 선언
    weight = np.random.normal(RND_mean, RND_std, [input_cnt, output_cnt]) 
    bias = np.random.normal(RND_mean, RND_std,[output_cnt])

model_init()

In [61]:
weight

array([[ 0.22239961],
       [-1.443217  ],
       [-0.75635231],
       [ 0.81645401],
       [ 0.75044476],
       [-0.45594693],
       [ 1.18962227],
       [-1.69061683],
       [-1.35639905],
       [-1.23243451]])

In [62]:
def model_init_return():
    weight = np.random.normal(RND_mean, RND_std, [input_cnt, output_cnt]) 
    bias = np.random.normal(RND_mean, RND_std,[output_cnt])
    return weight, bias

In [79]:
def import_data():
    import csv
    global data
    with open('data/abalone_mini.csv') as csvfile:
        csv_reader = csv.reader(csvfile)
        #print(type(csv_reader))

        rows = []
        for row in csv_reader:
            rows.append(row)

        #print(rows)

        data = np.zeros([5,11])

        for n,row in enumerate(rows):
            #print(row)
            if row[0] == 'I':data[n,0] = 1
            elif row[0] == 'M':data[n,1] = 1
            elif row[0] == 'F':data[n,2] = 1

            data[n, 3:] = row[1:]
        

In [88]:
def train_and_test(x):
    forward_neuralnet(data[:,:-1])

In [89]:
def forward_neuralnet(x):
    y = np.matmul(x, weight) + bias
    
    return y

In [90]:
def main_exec():
    data = import_data()
    model_init()
    y = train_and_test(data)
    print(y)

In [94]:
# 독립 변수
data[:,:-1]

array([[0.    , 1.    , 0.    , 0.455 , 0.365 , 0.095 , 0.514 , 0.2245,
        0.101 , 0.15  ],
       [0.    , 1.    , 0.    , 0.35  , 0.265 , 0.09  , 0.2255, 0.0995,
        0.0485, 0.07  ],
       [0.    , 0.    , 1.    , 0.53  , 0.42  , 0.135 , 0.677 , 0.2565,
        0.1415, 0.21  ],
       [0.    , 1.    , 0.    , 0.44  , 0.365 , 0.125 , 0.516 , 0.2155,
        0.114 , 0.155 ],
       [1.    , 0.    , 0.    , 0.33  , 0.255 , 0.08  , 0.205 , 0.0895,
        0.0395, 0.055 ]])

In [96]:
# 종속 변수
data[:,-1:]

array([[15.],
       [ 7.],
       [ 9.],
       [10.],
       [ 7.]])

In [97]:
display(forward_neuralnet(data[:,:-1]))

array([[-0.16671613],
       [ 0.28968368],
       [-1.50675989],
       [-0.16765696],
       [ 0.03935715]])

In [98]:
def forward_postproc(output, y):
    print('output : ', output)
    print('y :', y)
    # difference 편차
    diff = (output-y)
    print('diff = ', diff)
    # NumPy 제곱 매서드
    square = np.square(diff)
    print('square = ', square)
    # NumPy 평균 매서드
    loss = np.mean(square)
    print('loss = ', loss)
    
    return loss

In [99]:
forward_postproc(forward_neuralnet(data[:,:-1]),data[:,-1:])

output :  [[-0.16671613]
 [ 0.28968368]
 [-1.50675989]
 [-0.16765696]
 [ 0.03935715]]
y : [[15.]
 [ 7.]
 [ 9.]
 [10.]
 [ 7.]]
diff =  [[-15.16671613]
 [ -6.71031632]
 [-10.50675989]
 [-10.16765696]
 [ -6.96064285]]
square =  [[230.02927821]
 [ 45.02834509]
 [110.39200332]
 [103.38124808]
 [ 48.45054885]]
loss =  107.45628471247683


107.45628471247683

In [100]:
def run_train(x, y):
    output = forward_neuralnet(x)
    cost = forward_postproc(output, y)
    
    return output, cost

In [102]:
print(run_train(data[:,:-1], data[:,-1:]))

output :  [[-0.16671613]
 [ 0.28968368]
 [-1.50675989]
 [-0.16765696]
 [ 0.03935715]]
y : [[15.]
 [ 7.]
 [ 9.]
 [10.]
 [ 7.]]
diff =  [[-15.16671613]
 [ -6.71031632]
 [-10.50675989]
 [-10.16765696]
 [ -6.96064285]]
square =  [[230.02927821]
 [ 45.02834509]
 [110.39200332]
 [103.38124808]
 [ 48.45054885]]
loss =  107.45628471247683
(array([[-0.16671613],
       [ 0.28968368],
       [-1.50675989],
       [-0.16765696],
       [ 0.03935715]]), 107.45628471247683)
