In [1]:
import pandas as pd

df = pd.read_csv('data/liverpool.csv')
print(df)

              Name Position  Born  Number Nationality
0  Roberto Firmino       FW  1991   no. 9      Brazil
1       Sadio Mane       FW  1992  no. 10     Senegal
2    Mohamed Salah       FW  1992  no. 11       Egypt
3        Joe Gomez       DF  1997  no. 12     England
4   Alisson Becker       GK  1992  no. 13      Brazil


In [2]:
df

Name Position  Born  Number Nationality
0  Roberto Firmino       FW  1991   no. 9      Brazil
1       Sadio Mane       FW  1992  no. 10     Senegal
2    Mohamed Salah       FW  1992  no. 11       Egypt
3        Joe Gomez       DF  1997  no. 12     England
4   Alisson Becker       GK  1992  no. 13      Brazil

### NumPy

In [3]:
import numpy

In [4]:
array1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.shape

(11,)

In [7]:
array2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
type(array2)  # ndarray = n dimenstional array

numpy.ndarray

In [9]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
array2.shape

(3, 4)

In [11]:
array1.size

11

In [12]:
array2.size

12

In [13]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
    
print(array1)

[ 2  3  5  7 11 13 17 19 23 29 31]


In [14]:
array1 = numpy.full(6, 7)
    
print(array1)

[7 7 7 7 7 7]


In [15]:
array1 = numpy.full(6, 0)
array2 = numpy.zeros(6, dtype=int)
    
print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [16]:
array1 = numpy.full(6, 1)
array2 = numpy.ones(6, dtype=int)
    
print(array1)
print()
print(array2)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


In [17]:
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)
    
print(array1)
print()
print(array2)

[0.3903574  0.66887298 0.77808128 0.24918106 0.12017403 0.86855333]

[0.76487436 0.23381056 0.80420184 0.10140331 0.90313938 0.40611238]


In [18]:
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


In [19]:
array1 = numpy.arange(2, 7)
print(array1)

[2 3 4 5 6]


In [20]:
array1 = numpy.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]


In [21]:
import numpy as np

array1 = np.full(6, 0)
array2 = np.zeros(6)
array3 = np.full(6,6)
array4 = np.ones(9)
array5 = np.random.random(6)

In [22]:
import matplotlib.pyplot as plt

In [23]:
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [24]:
#1부터 100까지(1과 100 포함) 중 3의 배수만 담겨 있는 numpy array를 생성

arr = np.arange(3,101,3)

arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [25]:
list1 = [2,3,5,7,11,13,17,19,23,29,31]

array1 = np.array(list1)

In [26]:
array1[0]

2

In [27]:
array1[2]

5

In [28]:
array1[-1]

31

In [29]:
array1[-2]

29

In [30]:
array1[[1,3,4]]

array([ 3,  7, 11])

In [31]:
array2 = np.array([2,1,3])

In [32]:
array1[array2] # numpy array로 인덱싱

array([5, 3, 7])

In [33]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [34]:
array1[0:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [35]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [36]:
array1[2:]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [37]:
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

In [38]:
array1[2:11:3]

array([ 5, 13, 23])

### numpy 기본 연산

In [39]:
array1 = np.arange(10)
array2 = np.arange(10,20)

In [40]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
for i in range(len(array1)):
    array1[i] = 2 * array1[i]
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
array1 = np.arange(10)
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [45]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [47]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
array1 = array1*2

In [49]:
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
array1 = np.arange(10)
array2 = np.arange(10,20)

In [51]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [53]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [54]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [55]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])