### NumPy : 배열( 동일 자료형 집합 ) 처리, 배열 처리 함수

In [1]:
!conda search numpy

Loading channels: ...working... done
# Name                       Version           Build  Channel             
numpy                          1.9.3  py27he0c0ee4_6  pkgs/main           
numpy                          1.9.3  py27he0c0ee4_7  pkgs/main           
numpy                          1.9.3  py27he78448b_2  pkgs/main           
numpy                          1.9.3  py35h0e52b17_2  pkgs/main           
numpy                          1.9.3  py35hd5b3723_7  pkgs/main           
numpy                          1.9.3  py36hd5b3723_5  pkgs/main           
numpy                          1.9.3  py36hd5b3723_6  pkgs/main           
numpy                          1.9.3  py36hd5b3723_7  pkgs/main           
numpy                          1.9.3  py37hd5b3723_5  pkgs/main           
numpy                          1.9.3  py37hd5b3723_6  pkgs/main           
numpy                          1.9.3  py37hd5b3723_7  pkgs/main           
numpy                         1.11.3 py27h239e66a_11  pkgs/main

numpy                         1.14.6  py27h22e7547_4  pkgs/main           
numpy                         1.14.6  py27h22e7547_5  pkgs/main           
numpy                         1.14.6  py35hc27ee41_4  pkgs/main           
numpy                         1.14.6  py36ha06f490_5  pkgs/main           
numpy                         1.14.6  py36hc27ee41_4  pkgs/main           
numpy                         1.14.6  py37ha06f490_5  pkgs/main           
numpy                         1.14.6  py37hc27ee41_4  pkgs/main           
numpy                         1.14.6  py38h59abe10_4  pkgs/main           
numpy                         1.15.0  py27h911edcf_0  pkgs/main           
numpy                         1.15.0  py35h9fa60d3_0  pkgs/main           
numpy                         1.15.0  py36h9fa60d3_0  pkgs/main           
numpy                         1.15.0  py37h9fa60d3_0  pkgs/main           
numpy                         1.15.1  py27h22e7547_0  pkgs/main           
numpy                    

### Pandas : 데이터 분석용 라이브러리

In [2]:
!conda search pandas

Loading channels: ...working... done
# Name                       Version           Build  Channel             
pandas                        0.20.3  py27he04484b_2  pkgs/main           
pandas                        0.20.3  py35he2ce742_2  pkgs/main           
pandas                        0.20.3  py36hce827b7_2  pkgs/main           
pandas                        0.21.0  py27h3b50df0_1  pkgs/main           
pandas                        0.21.0  py27he42dcfb_0  pkgs/main           
pandas                        0.21.0  py35h0510043_1  pkgs/main           
pandas                        0.21.0  py35haac58f6_0  pkgs/main           
pandas                        0.21.0  py36ha94a700_0  pkgs/main           
pandas                        0.21.0  py36he09d4dd_1  pkgs/main           
pandas                        0.21.1  py27h5a33001_0  pkgs/main           
pandas                        0.21.1  py35h047fa9f_0  pkgs/main           
pandas                        0.21.1  py36h047fa9f_0  pkgs/main

### Matplotlib, seaborn : 데이터 시각화 라이브러리

In [3]:
!conda search Matplotlib

Loading channels: ...working... done
# Name                       Version           Build  Channel             
matplotlib                     2.0.2  py27hd2e917d_1  pkgs/main           
matplotlib                     2.0.2  py35h9bd10b2_1  pkgs/main           
matplotlib                     2.0.2  py36h58ba717_1  pkgs/main           
matplotlib                     2.1.0  py27h86412ea_0  pkgs/main           
matplotlib                     2.1.0  py35hea29350_0  pkgs/main           
matplotlib                     2.1.0  py36h11b4b9c_0  pkgs/main           
matplotlib                     2.1.1  py27h3be7b3c_0  pkgs/main           
matplotlib                     2.1.1  py35h2062329_0  pkgs/main           
matplotlib                     2.1.1  py36h2062329_0  pkgs/main           
matplotlib                     2.1.2  py27ha51faf0_0  pkgs/main           
matplotlib                     2.1.2  py35h016c42a_0  pkgs/main           
matplotlib                     2.1.2  py36h016c42a_0  pkgs/main

In [4]:
!conda list numpy # python 개발환경이라면, pip list <라이브러리명>

# packages in environment at C:\projects\Anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.19.2           py38hadc3359_0  
numpy-base                1.19.2           py38ha3acd2a_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  


In [5]:
!conda list pandas

# packages in environment at C:\projects\Anaconda3:
#
# Name                    Version                   Build  Channel
pandas                    1.1.3            py38ha925a31_0  


In [6]:
!conda list matplotlib

# packages in environment at C:\projects\Anaconda3:
#
# Name                    Version                   Build  Channel
matplotlib                3.3.2                         0  
matplotlib-base           3.3.2            py38hba9282a_0  


In [7]:
!conda list seaborn

# packages in environment at C:\projects\Anaconda3:
#
# Name                    Version                   Build  Channel
seaborn                   0.11.0                     py_0  


## NumPy

### NumPy Import

In [8]:
import numpy as np # numpy는 np라는 alias를 암묵적으로 사용한다.

In [9]:
np.__version__

'1.19.2'

In [10]:
# ndarray 객체(배열) 확익용 함수
def asprint(arr):
    print(f'type = {type(arr)}')
    print(f'shape = {arr.shape}, dimension = {arr.ndim}', end='')
    print(f'dtype = {arr.dtype}')
    print(f"Array's data:\n",arr)

## NumPy 배열 생성

### 파이썬 list로 NumPy 배열 생성

In [11]:
a = np.array([1,2,3])
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3,), dimension = 1dtype = int32
Array's data:
 [1 2 3]


In [13]:
l = [1,2,3]
a = np.array(l)
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3,), dimension = 1dtype = int32
Array's data:
 [1 2 3]


In [14]:
a = np.array(l, dtype = float)
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3,), dimension = 1dtype = float64
Array's data:
 [1. 2. 3.]


In [16]:
a = np.array(l, dtype = np.int64)
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3,), dimension = 1dtype = int64
Array's data:
 [1 2 3]


In [17]:
a = np.array([1,2,'a'])
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3,), dimension = 1dtype = <U11
Array's data:
 ['1' '2' 'a']


In [18]:
# 2차원 배열 생성
a = np.array([[1,2], [3,4],
            [5,6],[7,8]])
asprint(a)

type = <class 'numpy.ndarray'>
shape = (4, 2), dimension = 2dtype = int32
Array's data:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
# 3차원 배열 생성
a = np.array([[[1,2],[3,4],
              [4,5],[6,7]],
              [[9,10],[11,12],
              [13,14],[15,16]]])
asprint(a)

type = <class 'numpy.ndarray'>
shape = (2, 4, 2), dimension = 3dtype = int32
Array's data:
 [[[ 1  2]
  [ 3  4]
  [ 4  5]
  [ 6  7]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
