In [1]:
import numpy as np

In [2]:
# ndarray 객체(배열) 확익용 함수
def asprint(arr):
    # ndarrray 객체 속성( attribute )
    #
    # shape : ndarray 객체 구조
    # ndim : ndarray 객체 차원
    # dtype : ndarray 객체 자료형
    print(f'type = {type(arr)}')
    print(f'shape = {arr.shape}, dimension = {arr.ndim}', end='')
    print(f'dtype = {arr.dtype}')
    print(f"Array's data:\n",arr)

## 배열 크기 변환
### resize() 매서드 : 요소 수 자체가 변화하여 요소 수가 변화되도 에러가 발생하지 않음

In [3]:
a = np.random.randint(1,10,(2,6))
asprint(a)

type = <class 'numpy.ndarray'>
shape = (2, 6), dimension = 2dtype = int32
Array's data:
 [[6 4 4 3 3 2]
 [1 1 8 9 9 7]]


In [4]:
a.resize((6,2)) # 배열 요소 개수 변화가 없는 경우
asprint(a)

type = <class 'numpy.ndarray'>
shape = (6, 2), dimension = 2dtype = int32
Array's data:
 [[6 4]
 [4 3]
 [3 2]
 [1 1]
 [8 9]
 [9 7]]


In [5]:
a.resize((2,10)) # 배열 요소 개수가 증가한 경우
asprint(a)

type = <class 'numpy.ndarray'>
shape = (2, 10), dimension = 2dtype = int32
Array's data:
 [[6 4 4 3 3 2 1 1 8 9]
 [9 7 0 0 0 0 0 0 0 0]]


In [6]:
a.resize((3,3)) # 배열 요소 개수가 감소한 경우
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[6 4 4]
 [3 3 2]
 [1 1 8]]


## 배열 요소 추가 / 삭제
### append() 함수 : 배열 끝에 값을 추가하는 함수 축을 지정하여 배열에 추가하는 방법을 지정

In [7]:
a = np.arange(1, 10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)

asprint(a)
asprint(b)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]


###  case 1 : axis를 지정하지 않는 경우

- axis를 지정하지 않으면 1차원 배열로 변화 후 추가

In [8]:
result = np.append(a,b)
asprint(result)

type = <class 'numpy.ndarray'>
shape = (18,), dimension = 1dtype = int32
Array's data:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


### case 2 : axis = 0 지정

- shape 0을 제외한 나머지 shape은 같아야 한다. 만약 같지 않으면 append 시 오류 발생

In [9]:
result = np.append(a,b, axis=0)
asprint(result)

type = <class 'numpy.ndarray'>
shape = (6, 3), dimension = 2dtype = int32
Array's data:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [10]:
c = np.arange(10, 20).reshape(2,5)
asprint(c)

type = <class 'numpy.ndarray'>
shape = (2, 5), dimension = 2dtype = int32
Array's data:
 [[10 11 12 13 14]
 [15 16 17 18 19]]


In [11]:
result = np.append(a,c, axis=0)
asprint(result)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

###  case 3 :  axis = 1 지정

In [12]:
result = np.append(a,b, axis = 1)
asprint(result)

type = <class 'numpy.ndarray'>
shape = (3, 6), dimension = 2dtype = int32
Array's data:
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [15]:
c = np.arange(10, 20).reshape(5 ,2)
asprint(c)

type = <class 'numpy.ndarray'>
shape = (5, 2), dimension = 2dtype = int32
Array's data:
 [[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [16]:
result = np.append(a,c,axis = 1)
asprint(result)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 5

### insert  함수

In [17]:
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
np.insert(a,1,999) # a배열 1열에 999 삽입 (1차원으로 변환 후)

array([  1, 999,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
np.insert(a,1,999,axis=0) # 행방향 : a배열 1행에 999 삽입

array([[  1,   2,   3],
       [999, 999, 999],
       [  4,   5,   6],
       [  7,   8,   9]])

In [22]:
np.insert(a,1,999,axis=1) # 열방향 : a배열 1열에 999 삽입

array([[  1, 999,   2,   3],
       [  4, 999,   5,   6],
       [  7, 999,   8,   9]])

In [23]:
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### delete()

In [24]:
np.delete(a,1) # a배열 1열을 삭제 (1차원 배열로 변환 후)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.delete(a,1,axis = 0) # a배열 1행을 삭제

array([[1, 2, 3],
       [7, 8, 9]])

In [26]:
np.delete(a,1,axis = 1) # a배열 1열을 삭제

array([[1, 3],
       [4, 6],
       [7, 9]])

# NumPy 분석 실습

- 주요 데이터 형식으로 text file, excel file, json/XML file로 데이터를 제공
- CSV (Comma Separated Value) : 데이터 항목을 ','로 분리한 파일
- TSV (Tab Separated Value) : 데이터 항목을 'tab'으로 분리한 파일

### 1. 데이터 저장을 위한 파이썬  list 변수 정의

In [31]:
orders = []
names = []
heights = []

### 2. 데이터 읽기

In [32]:
with open('president_heights.csv','r') as f:
    lines = f.readline() # 제목줄 skip
    lines = f.readline() # 실제 필요한 데이터
    while lines: # EOF가 될때까지 반복
        #print(lines)
        data = lines.split(',')
        #print(data)
        
        orders.append(data[0])
        names.append(data[1])
        heights.append(int(data[2][:3]))
        
        lines = f.readline()

###  읽어드린 데이터의 일부 데이터 확인( 처음 5개, 마지막 5개)

In [33]:
orders[:5], orders[len(orders)-5:]

(['1', '2', '3', '4', '5'], ['40', '41', '42', '43', '44'])

In [34]:
names[:5], names[len(names)-5:]

(['George Washington',
  'John Adams',
  'Thomas Jefferson',
  'James Madison',
  'James Monroe'],
 ['Ronald Reagan',
  'George H. W. Bush',
  'Bill Clinton',
  'George W. Bush',
  'Barack Obama'])

In [36]:
heights[:5], heights[len(heights)-5:]

([189, 170, 189, 163, 183], [185, 188, 188, 182, 185])

### 4.NumPy 배열로 변환

In [41]:
order_array = np.array(orders)
name_array = np.array(names)
height_array = np.array(heights)

In [42]:
asprint(order_array)

type = <class 'numpy.ndarray'>
shape = (42,), dimension = 1dtype = <U2
Array's data:
 ['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16'
 '17' '18' '19' '20' '21' '23' '25' '26' '27' '28' '29' '30' '31' '32'
 '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43' '44']


In [43]:
asprint(name_array)

type = <class 'numpy.ndarray'>
shape = (42,), dimension = 1dtype = <U22
Array's data:
 ['George Washington' 'John Adams' 'Thomas Jefferson' 'James Madison'
 'James Monroe' 'John Quincy Adams' 'Andrew Jackson' 'Martin Van Buren'
 'William Henry Harrison' 'John Tyler' 'James K. Polk' 'Zachary Taylor'
 'Millard Fillmore' 'Franklin Pierce' 'James Buchanan' 'Abraham Lincoln'
 'Andrew Johnson' 'Ulysses S. Grant' 'Rutherford B. Hayes'
 'James A. Garfield' 'Chester A. Arthur' 'Benjamin Harrison'
 'William McKinley' 'Theodore Roosevelt' 'William Howard Taft'
 'Woodrow Wilson' 'Warren G. Harding' 'Calvin Coolidge' 'Herbert Hoover'
 'Franklin D. Roosevelt' 'Harry S. Truman' 'Dwight D. Eisenhower'
 'John F. Kennedy' 'Lyndon B. Johnson' 'Richard Nixon' 'Gerald Ford'
 'Jimmy Carter' 'Ronald Reagan' 'George H. W. Bush' 'Bill Clinton'
 'George W. Bush' 'Barack Obama']


In [44]:
asprint(height_array)

type = <class 'numpy.ndarray'>
shape = (42,), dimension = 1dtype = int32
Array's data:
 [189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


###  5. NumPy 제공 함수를 이용한 데이터 이해

In [48]:
print(f'최소 신장 : {height_array.min()} cm')
print(f'최고 신장 : {height_array.max()} cm')
print()
print(f'평균 신장 : {height_array.mean():.2f} cm')
print(f'분     산 : {height_array.var():.2f}')
print(f'표준 편차 : {height_array.std():.2f}')
print()
print(f'1사분위수 : {np.percentile(height_array, 25)} cm')
print(f'2사분위수 : {np.percentile(height_array, 50)} cm')
print(f'중 앙 값  : {np.median(height_array)} cm')
print(f'3사분위수 : {np.percentile(height_array, 75)} cm')
print(f'4사분위수 : {np.percentile(height_array, 100)} cm')

최소 신장 : 163 cm
최고 신장 : 193 cm

평균 신장 : 179.74 cm
분     산 : 48.05
표준 편차 : 6.93

1사분위수 : 174.25 cm
2사분위수 : 182.0 cm
중 앙 값  : 182.0 cm
3사분위수 : 183.0 cm
4사분위수 : 193.0 cm


In [49]:
print(f'최소 신장 대통령 : {height_array.min()} cm ( \
     {order_array[height_array.argmin()]}\
     {name_array[height_array.argmin()]})')

최소 신장 대통령 : 163 cm (      4     James Madison)


In [50]:
print(f'최고 신장 대통령 : {height_array.max()} cm ( \
     {order_array[height_array.argmax()]}\
     {name_array[height_array.argmax()]})')

최고 신장 대통령 : 193 cm (      16     Abraham Lincoln)


### 서울시 유동인구 데이터 이해 실습

In [51]:
dates = []
move_times = []
ages = []
sexs = []
citys = []
towns = []
move_peoples = []

In [52]:
with open('Floating_Population_2004.csv','r', encoding='UTF-8') as f:
    lines = f.readline() # 제목줄 skip
    lines = f.readline() # 실제 필요한 데이터
    while lines: # EOF가 될때까지 반복
        #print(lines)
        data = lines.split('","')
        #print(data)
        
        dates.append(data[0][1:])
        move_times.append(int(data[1][:5]))
        ages.append(int(data[2]))
        sexs.append(data[3])
        citys.append(data[4])
        towns.append(data[5])
        move_peoples.append(int(data[6][:-2]))
        
        lines = f.readline()
        

In [53]:
dates[:5], dates[len(dates)-5:]

(['20200401', '20200401', '20200401', '20200401', '20200401'],
 ['20200430', '20200430', '20200430', '20200430', '20200430'])

In [54]:
move_times[:5], move_times[len(move_times)-5:]

([0, 0, 0, 1, 1], [22, 22, 23, 23, 23])

In [55]:
ages[:5], ages[len(ages)-5:]

([20, 30, 50, 30, 40], [40, 50, 20, 30, 40])

In [56]:
sexs[:5], sexs[len(sexs)-5:]

(['남성', '여성', '남성', '여성', '남성'], ['여성', '여성', '여성', '여성', '남성'])

In [57]:
citys[:5], citys[len(citys)-5:]

(['서울', '서울', '서울', '서울', '서울'], ['서울', '서울', '서울', '서울', '서울'])

In [58]:
towns[:5], towns[len(towns)-5:]

(['도봉구', '동대문구', '구로구', '강남구', '동대문구'], ['성동구', '서대문구', '용산구', '서대문구', '강남구'])

In [59]:
move_peoples[:5], move_peoples[len(move_peoples)-5:]

([21490, 27260, 35670, 52380, 28420], [22150, 23270, 18570, 21100, 45730])

In [60]:
date_array = np.array(dates)
move_time_array = np.array(move_times)
age_array = np.array(ages)
sex_array = np.array(sexs)
city_array = np.array(citys)
town_array = np.array(towns)
move_people_array = np.array(move_peoples)

In [61]:
asprint(date_array)

type = <class 'numpy.ndarray'>
shape = (216000,), dimension = 1dtype = <U8
Array's data:
 ['20200401' '20200401' '20200401' ... '20200430' '20200430' '20200430']


In [62]:
asprint(move_time_array)

type = <class 'numpy.ndarray'>
shape = (216000,), dimension = 1dtype = int32
Array's data:
 [ 0  0  0 ... 23 23 23]


In [63]:
asprint(age_array)

type = <class 'numpy.ndarray'>
shape = (216000,), dimension = 1dtype = int32
Array's data:
 [20 30 50 ... 20 30 40]


In [64]:
asprint(sex_array)

type = <class 'numpy.ndarray'>
shape = (216000,), dimension = 1dtype = <U2
Array's data:
 ['남성' '여성' '남성' ... '여성' '여성' '남성']


In [65]:
asprint(city_array)

type = <class 'numpy.ndarray'>
shape = (216000,), dimension = 1dtype = <U2
Array's data:
 ['서울' '서울' '서울' ... '서울' '서울' '서울']


In [66]:
asprint(town_array)

type = <class 'numpy.ndarray'>
shape = (216000,), dimension = 1dtype = <U4
Array's data:
 ['도봉구' '동대문구' '구로구' ... '용산구' '서대문구' '강남구']


In [67]:
asprint(move_people_array)

type = <class 'numpy.ndarray'>
shape = (216000,), dimension = 1dtype = int32
Array's data:
 [21490 27260 35670 ... 18570 21100 45730]


In [68]:
print(f'최소 : {move_people_array.min()} 명')
print(f'최고 : {move_people_array.max()} 명')
print()
print(f'평균 : {move_people_array.mean():.2f} 명')
print(f'분산 : {move_people_array.var():.2f}')
print(f'표준 편차 : {move_people_array.std():.2f}')
print()
print(f'1사분위수 : {np.percentile(move_people_array, 25)} 명')
print(f'2사분위수 : {np.percentile(move_people_array, 50)} 명')
print(f'중 앙 값  : {np.median(move_people_array)} 명')
print(f'3사분위수 : {np.percentile(move_people_array, 75)} 명')
print(f'4사분위수 : {np.percentile(move_people_array, 100)} 명')

최소 : 4380 명
최고 : 120640 명

평균 : 27267.77 명
분산 : 155760322.70
표준 편차 : 12480.40

1사분위수 : 18070.0 명
2사분위수 : 25470.0 명
중 앙 값  : 25470.0 명
3사분위수 : 34090.0 명
4사분위수 : 120640.0 명


In [69]:
print(f'최소 : {move_people_array.min()} 명 ( \
     {date_array[move_people_array.argmin()]}\
     {move_time_array[move_people_array.argmin()]}\
     {age_array[move_people_array.argmin()]}\
     {sex_array[move_people_array.argmin()]}\
     {city_array[move_people_array.argmin()]}\
     {town_array[move_people_array.argmin()]})')

최소 : 4380 명 (      20200426     3     70     남성     서울     중구)


In [70]:
print(f'최고 : {move_people_array.max()} 명 ( \
     {date_array[move_people_array.argmax()]}\
     {move_time_array[move_people_array.argmax()]}\
     {age_array[move_people_array.argmax()]}\
     {sex_array[move_people_array.argmax()]}\
     {city_array[move_people_array.argmax()]}\
     {town_array[move_people_array.argmax()]})')

최고 : 120640 명 (      20200428     14     30     여성     서울     강남구)
