In [1]:
import numpy as np

In [2]:
# ndarray 객체(배열) 확익용 함수
def asprint(arr):
    # ndarrray 객체 속성( attribute )
    #
    # shape : ndarray 객체 구조
    # ndim : ndarray 객체 차원
    # dtype : ndarray 객체 자료형
    print(f'type = {type(arr)}')
    print(f'shape = {arr.shape}, dimension = {arr.ndim}', end='')
    print(f'dtype = {arr.dtype}')
    print(f"Array's data:\n",arr)

### NumPy 연산
## 산술 연산

In [5]:
a = np.arange(1,10).reshape((3,3))
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
b = np.arange(9, 0, -1).reshape((3,3))
asprint(b)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


### 사칙연산

In [7]:
a + b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [8]:
np.add(a,b)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [9]:
a - b

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [16]:
np.subtract(a,b)

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [12]:
a * b

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [13]:
np.multiply(a,b)

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [14]:
a / b

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [15]:
np.divide(a,b)

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

###  산술 연산

In [17]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [18]:
np.exp(b)

array([[8.10308393e+03, 2.98095799e+03, 1.09663316e+03],
       [4.03428793e+02, 1.48413159e+02, 5.45981500e+01],
       [2.00855369e+01, 7.38905610e+00, 2.71828183e+00]])

In [19]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [20]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [21]:
np.cos(b)

array([[-0.91113026, -0.14550003,  0.75390225],
       [ 0.96017029,  0.28366219, -0.65364362],
       [-0.9899925 , -0.41614684,  0.54030231]])

In [23]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [24]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [25]:
# dot product(내적)
np.dot(a,b)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

###  비교 연산
#### 배열 요소간 비교

In [26]:
a == b

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [27]:
a > b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

#### 배열 비교

In [28]:
np.array_equal(a,b)

False

In [29]:
np.array_equal(a,a)

True

### 집계함수

In [31]:
# 합계 : sum() 매서드, numpy.sum() 함수
a.sum(), np.sum(a)

(45, 45)

In [35]:
a.sum(axis = 0), np.sum(a, axis = 0) # 행 방향

(array([12, 15, 18]), array([12, 15, 18]))

In [34]:
a.sum(axis = 1), np.sum(a, axis = 1) # 열 방향

(array([ 6, 15, 24]), array([ 6, 15, 24]))

In [36]:
# 최소값 : min() 매서드, numpy.min()
a.min(), np.min(a)

(1, 1)

In [52]:
a.min(axis = 0), np.min(a, axis = 0)

(array([1, 2, 3]), array([1, 2, 3]))

In [53]:
a.min(axis = 1), np.min(a, axis = 1)

(array([1, 4, 7]), array([1, 4, 7]))

In [54]:
# 최대값 : max() 매서드, numpy.max()
a.max(), np.max(a)

(9, 9)

In [38]:
a.max(axis = 0), np.max(a, axis = 0)

(array([7, 8, 9]), array([7, 8, 9]))

In [47]:
a.max(axis = 1), np.max(a, axis = 1)

(array([3, 6, 9]), array([3, 6, 9]))

In [43]:
# 누적합 : cumsum() 매서드, numpy.cumsum() 함수
a.cumsum(), np.cumsum(a)

(array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32),
 array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32))

In [45]:
a.cumsum(axis = 0), np.cumsum(a, axis = 0)

(array([[ 1,  2,  3],
        [ 5,  7,  9],
        [12, 15, 18]], dtype=int32),
 array([[ 1,  2,  3],
        [ 5,  7,  9],
        [12, 15, 18]], dtype=int32))

In [46]:
a.cumsum(axis = 1), np.cumsum(a, axis = 1)

(array([[ 1,  3,  6],
        [ 4,  9, 15],
        [ 7, 15, 24]], dtype=int32),
 array([[ 1,  3,  6],
        [ 4,  9, 15],
        [ 7, 15, 24]], dtype=int32))

In [48]:
# 중앙값 : numpy.median()  - 매서드 없음
np.median(a)

5.0

In [49]:
np.median(a , axis = 0)

array([4., 5., 6.])

In [50]:
np.median(a , axis = 1)

array([2., 5., 8.])

In [51]:
# 상관 계수( correlation coeficient )
np.corrcoef(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
# 표준 편차 : std() 매서드, numpy.std()
a.std(), np.std(a)

(2.581988897471611, 2.581988897471611)

In [57]:
a.std(axis = 0), np.std(a , axis = 0)

(array([2.44948974, 2.44948974, 2.44948974]),
 array([2.44948974, 2.44948974, 2.44948974]))

In [58]:
a.std(axis = 1), np.std(a , axis = 1)

(array([0.81649658, 0.81649658, 0.81649658]),
 array([0.81649658, 0.81649658, 0.81649658]))

In [60]:
# 분산 : var() 메서드, numpy.var() 함수, 데이터가 퍼져 있는 정도 제곱이 되어 큰값이 나온다.
a.var(), np.var(a)

(6.666666666666667, 6.666666666666667)

In [61]:
a.var(axis = 0), np.var(a, axis = 0)

(array([6., 6., 6.]), array([6., 6., 6.]))

In [62]:
a.var(axis = 1), np.var(a, axis = 1)

(array([0.66666667, 0.66666667, 0.66666667]),
 array([0.66666667, 0.66666667, 0.66666667]))

### 사분위수 : numpy.percentile()

In [69]:
# 1사분위수 : 하위 25% 값
# 2사분위수 : 하위 50% 값 == 중앙값과 같은 값
# 3사분위수 : 하위 75% 값
print(f'1사분위수 : {np.percentile(a, 25)}')
print(f'2사분위수 : {np.percentile(a, 50)}')
print(f'3사분위수 : {np.percentile(a, 75)}')
#print(f'4사분위수 : {np.percentile(a, 100)}') ??

1사분위수 : 0.21556186731035146
2사분위수 : 0.515503031122124
3사분위수 : 0.7523509044515617
4사분위수 : 0.9772372274312491


In [67]:
a = np.random.random((100, ))
asprint(a)

type = <class 'numpy.ndarray'>
shape = (100,), dimension = 1dtype = float64
Array's data:
 [0.80132745 0.58693971 0.21440373 0.37037023 0.21099079 0.1899021
 0.80278588 0.8088611  0.34288788 0.09034297 0.19225021 0.70463792
 0.21505717 0.22227241 0.79519321 0.71182869 0.0387537  0.93176128
 0.50332622 0.62587651 0.36059738 0.80368346 0.3550236  0.94082105
 0.08285159 0.64807405 0.33282601 0.68828632 0.37600692 0.02765749
 0.52043848 0.4632395  0.68650269 0.63646834 0.45746283 0.41412892
 0.59354743 0.05672821 0.2248916  0.34065413 0.15876791 0.65861652
 0.56099351 0.34790772 0.90034037 0.93779377 0.3760914  0.9219742
 0.40286056 0.94926406 0.30274209 0.5177472  0.14442255 0.00874969
 0.62446035 0.11110995 0.6828056  0.11562335 0.69075967 0.54723465
 0.83125221 0.10836403 0.97716002 0.15652363 0.08468295 0.84912435
 0.62338598 0.79834679 0.97205092 0.09604374 0.50779479 0.10276083
 0.73807014 0.96525623 0.92968414 0.00748098 0.47551815 0.08649803
 0.2157301  0.57486091 0.92470113 0.5132

In [68]:
print(f'최소값 : {a.min():10.4f}\n')
print(f'1사분위수 : {np.percentile( a, 25 ):10.4f}')
print(f'2사분위수 : {np.percentile( a, 50 ):10.4f}\n')
print(f'중 앙 값  : {np.median( a ):10.4f}')
print(f'평 균 값  : {a.mean():10.4f}\n')
print(f'3사분위수 : {np.percentile( a, 75 ):10.4f}\n')
print(f'최 대 값  : {a.max():10.4f}\n')
print(f'분    산  : {a.var():10.4f}')
print(f'표준편차  : {a.std():10.4f}')

최소값 :     0.0075

1사분위수 :     0.2156
2사분위수 :     0.5155

중 앙 값  :     0.5155
평 균 값  :     0.5016

3사분위수 :     0.7524

최 대 값  :     0.9772

분    산  :     0.0877
표준편차  :     0.2961


In [70]:
a = np.arange(1, 11)
asprint(a)

type = <class 'numpy.ndarray'>
shape = (10,), dimension = 1dtype = int32
Array's data:
 [ 1  2  3  4  5  6  7  8  9 10]


In [72]:
# 최대값 인덱스
np.argmax(a)

9

In [73]:
# 최소값 인덱스
np.argmin(a)

0

In [74]:
idx = np.argmax(a)
print(f'a 배열의 최대값은 : {a[idx]}[{idx}]')

a 배열의 최대값은 : 10[9]


In [76]:
idx = np.argmin(a)
print(f'a 배열의 최소값은 : {a[idx]}[{idx}]')

a 배열의 최소값은 : 1[0]


###  브로드캐스팅

![브로드캐스팅](./broadcasting.png)

### 브로드캐스트 규칙

#### 규칙 1 : 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞쪽( 왼쪽 ) 을 1로 채운다.
#### 규칙 2 : 두 배열의 형상이 어떤 차원에서도 일치하지 않는다면 해당 차원 형상이 1인 배열이 다른 형상과 일치하도록 늘어난다.
#### 규칙 3 : 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생한다.

In [77]:
M = np.ones((2,3))
asprint(M)

type = <class 'numpy.ndarray'>
shape = (2, 3), dimension = 2dtype = float64
Array's data:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [81]:
a = np.arange(3)
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3,), dimension = 1dtype = int32
Array's data:
 [0 1 2]


### 브로드캐스트 과정

*  두 배열의 형상   

M.shape=(2,3)   
a.shape=(3,)

* 규칙 1에 따라 배열 a가 더 작은 차원을 가지므로 왼쪽을 1로 채운다.

M.shape=(2,3)   
a.shape=(1,3)

* 규칙 2에 따라 첫 번째 차원이 일치하지 않으므로 차원이 일치하도록 늘려준다.

M.shape=(2,3)   
a.shape=(1,3)

* 모양이 일치하므로 최종 형상이 (2,3)이 된다.

In [80]:
M + a  # 내부적으로 브로드캐스팅이 일어났다!

array([[1., 2., 3.],
       [1., 2., 3.]])

### 브로드캐스트 예제 2

In [83]:
a = np.arange(3).reshape((3,1)) # 열이 하나인 2차원 배열
asprint(a)

b = np.arange(3)
asprint(b)

type = <class 'numpy.ndarray'>
shape = (3, 1), dimension = 2dtype = int32
Array's data:
 [[0]
 [1]
 [2]]
type = <class 'numpy.ndarray'>
shape = (3,), dimension = 1dtype = int32
Array's data:
 [0 1 2]


### 브로드캐스트 과정

*  두 배열의 형상   

M.shape=(3,1)   
a.shape=(3,)

* 규칙 1에 따라 배열 b의 형상에 1을 덧붙인다.

M.shape=(3,1)   
a.shape=(1,3)

* 규칙 2에 따라 첫 번째 차원이 일치하지 않으므로 차원이 일치하도록 늘려준다.

M.shape=(3,1)   
a.shape=(1,3)

* 모양이 일치하므로 최종 형상이 (3,3)이 된다.

In [84]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 브로드캐스트 예제 3

In [85]:
M = np.ones((3,2))
asprint(M)
a = np.arange(3)
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3, 2), dimension = 2dtype = float64
Array's data:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
type = <class 'numpy.ndarray'>
shape = (3,), dimension = 1dtype = int32
Array's data:
 [0 1 2]


### 브로드캐스트 과정

*  두 배열의 형상   

M.shape=(3,2)   
a.shape=(3)

* 규칙 1에 따라 배열 a의 왼쪽에 1을 추가하여 차원을 일치시킨다.

M.shape=(3,2)   
a.shape=(1,3)

* 규칙 2에 따라 두 배열의 형상이 일치 하지 않으므로 1인 배열인 a를 M에 맞게 늘려준다.

M.shape=(3,2)   
a.shape=(3,3)

* 규칙 3에서 최종 형상이 서로 일치하지 않으므로 두 배열에 대한 연산은 실패한다.

In [87]:
M + a # 브로드 캐스팅이 안됨

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

* 브로드캐스트 예제 3번과 같이 브로드캐스트 과정시 error가 발생하는 경우 브로드캐스트 브로드캐스트 과정에서 error가 발생하지 않도록 미리 배열 형상을 맞추어 준다.
* 브로드캐스트 예제 3번에서는 a 배열을 미리 2차원 형상으로 변경한다. 이때 numpy.newaxis 상수를 사용한다.

In [91]:
a.shape, M.shape

((3,), (3, 2))

In [89]:
a[:, np.newaxis].shape # np.newaxis = 상수

(3, 1)

In [90]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

### NumPy  배열 벡터 연산과 제어문을 이용한 연산 속도 비교

In [92]:
a = np.arange(10000000)
a.shape

(10000000,)

In [95]:
result = 0

In [96]:
!pip install ipython

In [106]:
%%time
for v in a:
    result += v
# for문을 사용한 계산

<timed exec>:2: RuntimeWarning: overflow encountered in long_scalars


Wall time: 4.72 s


In [107]:
%%time
result += a.sum()
# NumPy 집계 함수를 이용한 합 계산

Wall time: 9 ms


<timed exec>:1: RuntimeWarning: overflow encountered in long_scalars


### 배열 복사

In [108]:
a = np.random.randint(0,9,(3,3))
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[2 7 8]
 [8 4 7]
 [6 5 1]]


In [109]:
copy_a = np.copy(a)
asprint(copy_a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[2 7 8]
 [8 4 7]
 [6 5 1]]


In [110]:
copy_a[:,0] = 0
asprint(copy_a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[0 7 8]
 [0 4 7]
 [0 5 1]]


In [111]:
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[2 7 8]
 [8 4 7]
 [6 5 1]]


### 배열 정렬

In [112]:
org_a = np.random.randint(1,10,(3,3))
asprint(org_a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[1 1 8]
 [6 9 1]
 [1 8 3]]


In [114]:
copy_a = np.copy(org_a)
copy_b = np.copy(org_a)
copy_c = np.copy(org_a)

In [115]:
copy_a.sort(axis = 0) # axis = 0 행 방향 정렬
asprint(copy_a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[1 1 1]
 [1 8 3]
 [6 9 8]]


In [116]:
copy_b.sort(axis = 1) # axis = 1 열 방향 정렬
asprint(copy_b)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[1 1 8]
 [1 6 9]
 [1 3 8]]


In [118]:
np.sort(copy_c, axis = 0)[::-1]
asprint(copy_c)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[1 1 8]
 [6 9 1]
 [1 8 3]]


##  배열 변환
### 배열 전치( Transpose ) : 행과 열을 바꿔준다.

In [119]:
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[2 7 8]
 [8 4 7]
 [6 5 1]]


In [120]:
asprint(a.T)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[2 8 6]
 [7 4 5]
 [8 7 1]]


In [136]:
a = np.random.randint(1,10,(3,3))
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[3 7 7]
 [5 6 7]
 [1 8 4]]


In [122]:
np.transpose(a)

array([[2, 7, 6],
       [1, 5, 7],
       [1, 1, 8]])

### 배열 형태(구조) 변경
### ravel() 매서드

In [137]:
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[3 7 7]
 [5 6 7]
 [1 8 4]]


In [138]:
b = a.ravel() # 2차원을 1차원으로 변경
asprint(b)

type = <class 'numpy.ndarray'>
shape = (9,), dimension = 1dtype = int32
Array's data:
 [3 7 7 5 6 7 1 8 4]


In [139]:
b[2]=100
asprint(b)

type = <class 'numpy.ndarray'>
shape = (9,), dimension = 1dtype = int32
Array's data:
 [  3   7 100   5   6   7   1   8   4]


In [140]:
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3, 3), dimension = 2dtype = int32
Array's data:
 [[  3   7 100]
 [  5   6   7]
 [  1   8   4]]


### reshape()

In [142]:
a = np.random.randint(1,7,(3,2))
asprint(a)

type = <class 'numpy.ndarray'>
shape = (3, 2), dimension = 2dtype = int32
Array's data:
 [[4 5]
 [6 5]
 [1 4]]


In [144]:
result = a.reshape((3,2,1))
asprint(result)

type = <class 'numpy.ndarray'>
shape = (3, 2, 1), dimension = 3dtype = int32
Array's data:
 [[[4]
  [5]]

 [[6]
  [5]]

 [[1]
  [4]]]


In [147]:
a1 = np.arange(10)
a2 = a1.reshape((2,5))
a3 = a1.reshape((5,2))

In [148]:
asprint(a1)
asprint(a2)
asprint(a3)

type = <class 'numpy.ndarray'>
shape = (10,), dimension = 1dtype = int32
Array's data:
 [0 1 2 3 4 5 6 7 8 9]
type = <class 'numpy.ndarray'>
shape = (2, 5), dimension = 2dtype = int32
Array's data:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
type = <class 'numpy.ndarray'>
shape = (5, 2), dimension = 2dtype = int32
Array's data:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [150]:
# 실무적으로 많이 사용되는 사례 : -1은 자동으로 결정, 열은 5로 결정
a2 = a1.reshape((-1,5))
asprint(a2)

type = <class 'numpy.ndarray'>
shape = (2, 5), dimension = 2dtype = int32
Array's data:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [151]:
a3 = a1.reshape((5,-1))
asprint(a3)

type = <class 'numpy.ndarray'>
shape = (5, 2), dimension = 2dtype = int32
Array's data:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [152]:
asprint(a1)

type = <class 'numpy.ndarray'>
shape = (10,), dimension = 1dtype = int32
Array's data:
 [0 1 2 3 4 5 6 7 8 9]


In [153]:
# a1배열을 2차원으로 변환( 아주 많이 사용 )
a1.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### .tolist() 매서드 : NumPy 배열을 list로 변환

In [154]:
type(a1)

numpy.ndarray

In [155]:
type(a1.tolist())

list

In [156]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
a1.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]