In [1]:
import numpy as np

In [3]:
# comparisons
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# boolean array
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [4]:
# 하나라도 조건 만족시 True
np.any(a>5), np.any(a<0)

(True, False)

In [5]:
# 모두가 조건에 만족시 True
np.all(a>5), np.all(a<10)

(False, True)

In [7]:
# comparisons operations
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)
test_a > test_b

array([False,  True, False])

In [8]:
test_a == test_b

array([False, False, False])

In [9]:
(test_a > test_b).any()

True

In [13]:
(test_a > test_b).all()

False

In [14]:
a>0

array([ True,  True, False])

In [15]:
a<3

array([ True, False,  True])

In [10]:
a = np.array([1,3,0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [11]:
b = np.array([True,False,True], bool)
np.logical_not(b)

array([False,  True, False])

In [12]:
c = np.array([False,True,False], bool)
np.logical_or(b,c)

array([ True,  True,  True])

In [16]:
# np.where
# where(condition, True, False)
np.where(a > 0, 3, 2)

array([3, 3, 2])

In [17]:
# index 반환
a = np.arange(10)
np.where(a>5)

(array([6, 7, 8, 9], dtype=int64),)

In [18]:
# isnan
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [19]:
# isfinite
# 학습 발산되어버리면 감지
np.isfinite(a)

array([ True, False, False])

In [20]:
# argmax & argmin
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [21]:
# axis
a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

In [22]:
# argsort
a = np.array([1,2,4,5,8,78,23,3])
a.argsort()

array([0, 1, 7, 2, 3, 4, 6, 5], dtype=int64)

In [23]:
a.argsort()[::-1]

array([5, 6, 4, 3, 2, 7, 1, 0], dtype=int64)

In [24]:
# boolean index
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [25]:
test_array.shape

(8,)

In [26]:
(test_array > 3).shape

(8,)

In [27]:
condition = test_array > 3
test_array[condition]

array([4., 8., 9., 7.])

In [28]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [34]:
# fancy index
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b] # bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함



array([2., 2., 4., 8., 6., 4.])

In [35]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [36]:
# matrix
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
# b row index, c column index
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [ ]:
# numpy data i/o
# text file read
# a = np.loadtext("file_path")
# csv file save
# np.savetxt("save file_path .csv", save_data_variable, fmt="%.2e", delimiter=",")

In [40]:
# numpy object - npy
np.save("npy_test", arr=a)


In [41]:
a_test = np.load(file="npy_test.npy")
a_test

array([[ 1.,  4.],
       [ 9., 16.]])

In [43]:
npy_array = np.load(file="npy_test.npy")
npy_array[:1]

array([[1., 4.]])