In [2]:
import numpy as np

test_array = np.array([1, 4, 5, 8], float)

print(test_array)
print(test_array[3])
print(type(test_array[3]))

[1. 4. 5. 8.]
8.0
<class 'numpy.float64'>


In [3]:
# array 생성
a = [1, 2, 3, 4, 5]
a = np.array(a, int)
print(a)

[1 2 3 4 5]


In [4]:
test_array = np.array(["1", "4", 5.0, 8], float)
print(test_array)
print(type(test_array))

[1. 4. 5. 8.]
<class 'numpy.ndarray'>


In [5]:
# python list 와 numpy array 차이
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]
print("python list")
print(a[0] is b[-1])

a = np.array(a)
b = np.array(b)
print("numpy array")
print(a[0] is b[-1])

python list
True
numpy array
False


In [6]:
test_array.shape

(4,)

In [7]:
test_array.dtype

dtype('float64')

In [8]:
a = [[1,2,3],[4,5,6],[7,8,9]]
np.array(a).shape

(3, 3)

In [9]:
# rank 0 scalar
# rank 1 vector
# rank 2 matrix
# rank 3 3-tensor
# rank n n-tensor

In [10]:
# ndim - number of dimensions
np.array(a).ndim

2

In [11]:
# size - number of data 
np.array(a).size

9

In [14]:
# nbytes
print(np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float32).nbytes)
print(np.array([[1,2,3],[4.5,"5","6"]], dtype=np.int32).nbytes)
print(np.array([[1,2,3],[4.5,"5","6"]], dtype=np.int8).nbytes)
print(np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float64).nbytes)

24
24
6
48
