In [1]:
import numpy as np

In [2]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [4]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [5]:
# -1 : size를 기반으로 row 개수 선정
print(np.array(test_matrix).reshape(2,4).shape) 
print(np.array(test_matrix).reshape(-1,2).shape) 

(2, 4)
(4, 2)


In [7]:
print(np.array(test_matrix).reshape(2,2,2).shape)  
print(np.array(test_matrix).reshape(1,2,-1).shape)  

(2, 2, 2)
(1, 2, 4)


In [9]:
# flatten
print(np.array(test_matrix))
print(np.array(test_matrix).flatten())

[[1 2 3 4]
 [1 2 5 8]]
[1 2 3 4 1 2 5 8]


In [14]:
# indexing

np_matrix = np.array(test_matrix)

print(np_matrix)
print(np_matrix[0,0])
print(np_matrix[0][0])

[[1 2 3 4]
 [1 2 5 8]]
1
1


In [15]:
np_matrix[0,0] = 10
np_matrix

array([[10,  2,  3,  4],
       [ 1,  2,  5,  8]])

In [18]:
# slicing
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [21]:
a[1,1:3]

array([7, 8])

In [24]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

In [26]:
print(a[1])
print(a[1:3])

[ 6  7  8  9 10]
[[ 6  7  8  9 10]]


In [27]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [29]:
a[:,::2]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [30]:
a[::2,::3]

array([[ 0,  3,  6,  9],
       [20, 23, 26, 29],
       [40, 43, 46, 49],
       [60, 63, 66, 69],
       [80, 83, 86, 89]])

In [31]:
# creation function
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
np.arange(0, 5, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [35]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [36]:
# ones, zeros and empty
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [37]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [39]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.empty(shape=(10,), dtype=np.int8)

array([-112,   20,   69,  -75,    5,    2,    0,    0,    0,    0],
      dtype=int8)

In [54]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
# something_like
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [57]:
np.zeros_like(test_matrix, dtype=np.float32)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)

In [93]:
np.empty_like(test_matrix, dtype=np.float32)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)

In [94]:
# 단위행렬  identity
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [95]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
# eye
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [98]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [99]:
# diag 대각 행렬 값을 추출
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [100]:
np.diag(matrix, k=1)

array([1, 5])

In [101]:
# random sampling
# 균등분포
np.random.uniform(0, 1, 10).reshape(2,5)

array([[0.66021919, 0.70095714, 0.03367863, 0.94396161, 0.69295895],
       [0.5827943 , 0.67848926, 0.78436182, 0.11164475, 0.9946351 ]])

In [102]:
# 정규분포
np.random.normal(0, 1, 10).reshape(2,5)

array([[-2.03687133,  0.84745753, -0.55632904, -0.84835222, -0.40587201],
       [ 0.77693526,  0.77908174, -0.59720003, -1.17318462, -1.02548239]])

In [103]:
np.random.exponential(scale=2, size=100)

array([1.06597781, 3.33720832, 0.45915228, 0.27822398, 4.15565956,
       2.86905206, 0.36789228, 1.14712281, 0.11958352, 0.38980727,
       2.33128865, 0.14236346, 2.83565459, 1.07459379, 1.18337545,
       0.89737084, 4.93433914, 4.63992657, 0.94368158, 0.28350594,
       3.63574996, 1.30239286, 2.17917383, 0.62929141, 3.64403751,
       4.93696145, 1.34448192, 0.13636081, 3.3427762 , 1.85479521,
       0.37994601, 6.65904377, 1.95782582, 2.02464086, 0.42256788,
       1.44118066, 2.59587668, 3.09877422, 0.60855878, 0.12632802,
       0.12697599, 1.30365221, 0.37066822, 2.17885736, 0.83515322,
       2.3268189 , 0.40917146, 3.11879806, 2.21816066, 3.90673214,
       1.11380663, 3.19305392, 2.54934837, 2.49102347, 3.87402712,
       0.23838533, 4.12971996, 4.01804174, 1.63988608, 1.63308053,
       0.79963011, 3.67149101, 1.41641137, 1.59846154, 0.36532087,
       4.29941607, 0.59580908, 2.35569963, 1.75035181, 1.34995914,
       2.36092158, 0.7354596 , 1.19057876, 0.8038381 , 2.30126

In [107]:
# operation functions
# sum
test_array = np.arange(1, 11)
print(np.sum(test_array))
print(test_array.sum())

55
55


In [109]:
test_array = np.arange(1, 13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
# axis
test_array.sum(axis=1)

array([10, 26, 42])

In [113]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [114]:
# concatenate
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [116]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [117]:
# concatenate
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [119]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
b = b[np.newaxis, :]
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [120]:
# array operation
test_a = np.array([[1,2,3],[4,5,6]],float)
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [122]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [123]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [121]:
# Element-wise operations
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [124]:
# Dot product 행렬곱
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [125]:
# transpose 또는 T attribute 사용
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [129]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [127]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [131]:
# broadcasting
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [132]:
test_matrix = np.arange(1, 13).reshape(4,3)
test_vector = np.arange(10, 40, 10)
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [136]:
# numpy performance #1
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

iternation_max = 100000

vector = list(range(iternation_max))
scalar = 2

# for loop 성능 체크
%timeit scalar_vector_product(scalar, vector)

17 ms ± 1.68 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [137]:
# list comprehension을 이용한 성능 체크
%timeit [scalar * value for value in range(iternation_max)]

10.8 ms ± 91.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [138]:
# numpy를 이용한 성능 체크
%timeit np.arange(iternation_max) * scalar

199 µs ± 49.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
